return PlaceObj('ModDef', {
	'title', "Fistful",
	'description', "Bored Shooting the enemies, but you still wanna fight? You feel limited by the Combat Options for Melee? Then this mod is for you.\nIt contains several changes to the unarmed combat and to the combat with Knives. Such as Hit Zones for Punch Attacks, applying debuff on the target or the ability to move while throwing a knife. There is a new Perk Tree and there are some new Items as well, as well as new Roles for Mercs (for instance Blood is a Knife Expert, while Flay is a Melee Expert).\n\nItems\nMolotov: AP Cost 4, Burning AOE, Damage, moderate Mishap\nNew \nStones: Exposed Marked on target AP Cost 1\nThrowing Axe: AP Cost 3, Dmg 13 \nSands: Blind, Flank, Inaccurate, AP Cost 2\nBandages: +2%Crit, 7 DMG\nTrench Knife (Balanced + Sharpened)\nSet of Throwing Knifes (Infinite)\n\nNew Combine Recipes\n2 Sharpener = MeleeKnifeKit -> MeleeKnifeKit + Knife = Trench Knife \n2 Balancing Weights = KnifeThrowKit -> KnifeThowKit + Knife = Set of Throwing Knifes\nStim Pack = 10 Meds + 1 Glow Stick\nPipe Bomb = 10 Black Powder + 2 Fine Steel Pipes\n\nPerks\nAdded Perks: Martial Arts, Throwing, Hand to Hand\nNew Perks: \nBronze75+\nQuick Swap: Switch Weapons for free\nFray: +5 Grit when near Enemy/Ally\nSilver 85+\nNeuragic Point: Trickshot Melee+Throw\nNatural Stealth: +50% Stealth Bonus\nBattle Ready: +1AP, Free Move\nHintnRun: Free Move after Throw\nHitNCover: Grit after Throw\n\nUnique Perks\nSix Blade Knife: Six Knife Throw\n\nCombat Actions\nNew Unarmed Attacks:\nEyes: Blind \nLiver: Bleed\nPlexus: Numb\nTemple: Tired\nGut: Slow\n\nThrow Combat Actions\nStep and Stab: Throw Axe, Knife, and move, Blood Perk but nerfed, no Reset of Kill\nThrowing Axe: Throw Axe, like Knife Throw\n\nGeneralChanges to Combat Actions\nSneak: has its 2 AP Cost Removed\nDisarm: Cost increased to 4\nQuickFix: Weaker Heal, costing 1 AP\nCut: Cost reduced to 4 AP\nOpen/cClose Doors: 2AP\nWindowBreak: Cost Removed\n\nUI\nNew Specialzations:\nMelee Expert \nKnife Expert\n\nGame Rules\nMarksmanship will now also be increased by Kills with throwing weapons.\n\nNew Merc\nBloodmary, Melee Unit",
	'image', "Mod/bWKFbe/Images/FistfulBack.png",
	'last_changes', "Items\nMolotov: AP Cost 4, Burning AOE, Damage, moderate Mishap\nNew \nStones: Exposed Marked on target AP Cost 1\nThrowing Axe: AP Cost 3, Dmg 13 \nSands: Blind, Flank, Inaccurate, AP Cost 2\nBandages: +2%Crit, 7 DMG\nTrench Knife (Balanced + Sharpened)\nSet of Throwing Knifes (Infinite)\n\nNew Combine Recipes\n2 Sharpener = MeleeKnifeKit -> MeleeKnifeKit + Knife = Trench Knife \n2 Balancing Weights = KnifeThrowKit -> KnifeThowKit + Knife = Set of Throwing Knifes\nStim Pack = 10 Meds + 1 Glow Stick\nPipe Bomb = 10 Black Powder + 2 Fine Steel Pipes\nIED = 20 Parts + 10 Black Powder\n\nPerks\nAdded Perks: Martial Arts, Throwing, Hand to Hand\nNew Perks: \nBronze75+\nQuick Swap: Switch Weapons for free\nFray: +5 Grit when near Enemy/Ally\nSilver 85+\nNeuragic Point: Trickshot Melee+Throw\nNatural Stealth: +50% Stealth Bonus\nBattle Ready: +1AP, Free Move\nHintnRun: Free Move after Throw\nHitNCover: Grit after Throw\n\nUnique Perks\nSix Blade Knife: Six Knife Throw\n\nCombat Actions\nNew Unarmed Attacks:\nEyes: Blind \nLiver: Bleed\nPlexus: Numb\nTemple: Tired\nGut: Slow\n\nThrow Combat Actions\nStep and Stab: Throw Axe, Knife, and move, Blood Perk but nerfed, no Reset of Kill\nThrowing Axe: Throw Axe, like Knife Throw\n\nGeneralChanges to Combat Actions\nSneak: has its 2 AP Cost Removed\nDisarm: Cost increased to 4\nQuickFix: Weaker Heal, costing 1 AP\nCut: Cost reduced to 4 AP\nOpen/cClose Doors: 2AP\nWindowBreak: Cost Removed\n\nUI\nNew Specialzations:\nMelee Expert \nKnife Expert\n\nGame Rules\nMarksmanship will now also be increased by Kills with throwing weapons.\n\nNew Merc\nBloodmary, Melee Unit",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "JA3_CommonLib",
			'title', "JA3_CommonLib",
			'version_major', 1,
			'version_minor', 3,
		}),
	},
	'id', "bWKFbe",
	'author', "cockadoodledoo",
	'version', 1337,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"InventoryItem/SpecialThrowingKnifes.lua",
		"InventoryItem/IncredibleGoodKnife.lua",
		"InventoryItem/Bandages.lua",
		"InventoryItem/Molotov.lua",
		"InventoryItem/Stones.lua",
		"InventoryItem/ThrowingAxe.lua",
		"InventoryItem/Sands.lua",
		"CharacterEffect/QuickSwap.lua",
		"CharacterEffect/Fray.lua",
		"CharacterEffect/Throwing.lua",
		"CharacterEffect/HandtoHand.lua",
		"CharacterEffect/MartialArts.lua",
		"CharacterEffect/NeuralgicPoints.lua",
		"CharacterEffect/NaturalStealth.lua",
		"CharacterEffect/BattleReadyBuff.lua",
		"CharacterEffect/BattleReady.lua",
		"CharacterEffect/HitNRun.lua",
		"CharacterEffect/HitNCover.lua",
		"CharacterEffect/SixBladeKnife.lua",
		"UnitData/BloodyMary.lua",
		"InventoryItem/PermaStim.lua",
		"InventoryItem/ThrowKnifeKit.lua",
		"InventoryItem/MeleeKnifeKit.lua",
		"UnitData/Blood.lua",
		"UnitData/Igor.lua",
		"UnitData/Flay.lua",
		"UnitData/DrQ.lua",
	},
	'default_options', {},
	'has_data', true,
	'saved', 1731363016,
	'code_hash', 4936857518663406651,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A6",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "TestStuff",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "TestStuff_copy",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "SpecialThrowingKnifes",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "IncredibleGoodKnife",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Bandages",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Molotov",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Stones",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "ThrowingAxe",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Sands",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "QuickSwap",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "QuickSwap",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Fray",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Throwing",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "HandtoHand",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "MartialArts",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "NeuralgicPoints",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "NaturalStealth",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "BattleReadyBuff",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "BattleReady",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "HitNRun",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "HitNCover",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "Eyes",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "Liver",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "SolarPlexus",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "Temple",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "GutPunch",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "ThrowingAxe",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "StepandStab",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "KnifeBurst",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "SixBladeKnife",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "SixBladeKnife",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MercSpecializations",
			'Id', "KnifeExpert",
			'ClassDisplayName', "Merc Specializations",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MercSpecializations",
			'Id', "MeleeExpert",
			'ClassDisplayName', "Merc Specializations",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "Interact_WindowBreak",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "Interact_DoorClose",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "Interact_DoorOpen",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "Cut",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "Interact_Disarm",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "Hide",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "QuickFix",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "MiraLoadout",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "BloodyMary",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "PermaStim",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "BloodyMary",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "StatGainingPrerequisite",
			'Id', "Marksmanship",
			'ClassDisplayName', "Stat Gaining Prerequisite",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "RecipeDef",
			'Id', "ThrowKnifeKitCombine",
			'ClassDisplayName', "Combine recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "ThrowKnifeKit",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "RecipeDef",
			'Id', "ThrowKnifeCombi",
			'ClassDisplayName', "Combine recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "RecipeDef",
			'Id', "MeleeKnifeKitCombine",
			'ClassDisplayName', "Combine recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "MeleeKnifeKit",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "RecipeDef",
			'Id', "MeleeKnifeCombi",
			'ClassDisplayName', "Combine recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "RecipeDef",
			'Id', "PipeBomb",
			'ClassDisplayName', "Combine recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "RecipeDef",
			'Id', "StimRecipe",
			'ClassDisplayName', "Combine recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Blood",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Igor",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Flay",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "DrQ",
			'ClassDisplayName', "Unit",
		}),
	},
	'steam_id', "3361952672",
})