UndefineClass('Stones')
DefineClass.Stones = {
	__parents = { "Grenade" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Exposed Marked AP Cost 1",
	object_class = "Grenade",
	Repairable = false,
	Reliability = 100,
	Icon = "Mod/bWKFbe/Images/StonesItem 2.png",
	ItemType = "Grenade",
	DisplayName = T(928653772693, --[[ModItemInventoryItemCompositeDef Stones DisplayName]] "Stones"),
	DisplayNamePlural = T(158898954019, --[[ModItemInventoryItemCompositeDef Stones DisplayNamePlural]] "Stones"),
	Description = T(264612515674, --[[ModItemInventoryItemCompositeDef Stones Description]] "Good weighed Stones! The target gets <em>Exposed</em> and <em>Marked</em>."),
	AdditionalHint = T(457316660302, --[[ModItemInventoryItemCompositeDef Stones AdditionalHint]] "You can also use the stones to lure the enemy..."),
	UnitStat = "Strength",
	Cost = 150,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 10,
	RestockWeight = 25,
	CategoryPair = "Grenade",
	MinMishapChance = -2,
	MaxMishapChance = 5,
	MaxMishapRange = 8,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	CenterAppliedEffects = {
		"Exposed",
		"Marked",
	},
	AreaOfEffect = 1,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	AreaAppliedEffects = {
		"Exposed",
		"Marked",
	},
	PenetrationClass = 1,
	BurnGround = false,
	BaseDamage = 0,
	Scatter = 1,
	AttackAP = 1000,
	ThrowMaxRange = 17,
	Noise = 3,
	Entity = "Weapon_StunGrenadeM84",
	ActionIcon = "Mod/bWKFbe/Images/StoneThrow.png",
	MaxStacks = 20,
}

