UndefineClass('ThrowingAxe')
DefineClass.ThrowingAxe = {
	__parents = { "StackableMeleeWeapon" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "AP Cost 3, DMG 13",
	object_class = "StackableMeleeWeapon",
	ScrapParts = 1,
	Reliability = 50,
	Icon = "Mod/bWKFbe/Images/Axes.png",
	SubIcon = "UI/Icons/Weapons/balanced",
	DisplayName = T(280515189899, --[[ModItemInventoryItemCompositeDef ThrowingAxe DisplayName]] "Throwing Axe"),
	DisplayNamePlural = T(117239217757, --[[ModItemInventoryItemCompositeDef ThrowingAxe DisplayNamePlural]] "Throwing Axes"),
	Description = T(588506037257, --[[ModItemInventoryItemCompositeDef ThrowingAxe Description]] "Nothing like a well balanced traditional weapon."),
	AdditionalHint = T(208650022277, --[[ModItemInventoryItemCompositeDef ThrowingAxe AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Balanced - longer throwing range\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Balanced - increased bonus from Aiming\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Low attack costs"),
	UnitStat = "Dexterity",
	Cost = 1200,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 10,
	RestockWeight = 15,
	BaseChanceToHit = 100,
	CritChance = 5,
	CritChanceScaled = 3,
	BaseDamage = 13,
	AimAccuracy = 20,
	PenetrationClass = 4,
	DamageMultiplier = 100,
	CanThrow = true,
	WeaponRange = 12,
	AttackAP = 3000,
	MaxAimActions = 3,
	Noise = 1,
	Entity = "Weapon_Axe",
	fxClass = "ThrowingAxe",
	HolsterSlot = "Leg",
	CanAppearUsed = false,
}

